import { StyleSheet } from "react-native";
import { MAP_CARD_GAP, MAP_CARD_WIDTH, palette } from "../theme";

export const styleChunk4 = {
  homeLockerCardTitle: {
    flex: 1,
    color: "#202435",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "900",
  },
  homeLockerStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  homeLockerStatusOnline: {
    backgroundColor: "#dff2e5",
  },
  homeLockerStatusOffline: {
    backgroundColor: "#fde5cf",
  },
  homeLockerStatusText: {
    color: "#202435",
    fontSize: 11,
    fontWeight: "800",
  },
  homeLockerCardAddress: {
    color: "#6f7685",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 12,
  },
  homeLockerMetricsRow: {
    flexDirection: "row",
    gap: 10,
  },
  currentRentalCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 22,
    backgroundColor: "#ffffff",
    padding: 14,
    shadowColor: "#9ba3b8",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  currentRentalCardIdle: {
    backgroundColor: "#fff7ef",
    borderWidth: 1,
    borderColor: "rgba(176,100,66,0.12)",
  },
  currentRentalArtwork: {
    width: 96,
    height: 96,
    borderRadius: 18,
    backgroundColor: "#f6f6f7",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  currentRentalMain: {
    flex: 1,
    justifyContent: "center",
    gap: 10,
  },
  currentRentalTitle: {
    color: "#202435",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
  },
  currentRentalMeta: {
    color: "#6e7482",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  currentRentalBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "#e44d3c",
  },
  currentRentalBadgeIdle: {
    backgroundColor: "#f1e2d3",
  },
  currentRentalBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  currentRentalBadgeDotIdle: {
    backgroundColor: "#c36e45",
  },
  currentRentalBadgeText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  currentRentalBadgeTextIdle: {
    color: "#8a4f35",
  },
  currentRentalArrowWrap: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#f5f5f6",
    alignItems: "center",
    justifyContent: "center",
  },
  currentRentalArrowWrapIdle: {
    backgroundColor: "#f1e2d3",
  },
  currentRentalArrow: {
    color: "#202435",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "700",
  },
  currentRentalArrowIdle: {
    color: "#8a4f35",
  },
  homeNoticeCard: {
    borderRadius: 26,
    backgroundColor: "#fff7ef",
    borderWidth: 1,
    borderColor: "rgba(176,100,66,0.12)",
    padding: 18,
    gap: 8,
  },
  homeNoticeEyebrow: {
    color: "#a05b42",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  homeNoticeTitle: {
    color: "#202435",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
  },
  homeNoticeText: {
    color: "#6e7482",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  mapTabShell: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  mapSurface: {
    flex: 1,
    backgroundColor: "#f4f2eb",
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    overflow: "hidden",
  },
  nativeMap: {
    ...StyleSheet.absoluteFillObject,
  },
  mapTopOverlay: {
    position: "absolute",
    top: 14,
    left: 14,
    right: 14,
  },
  mapTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  mapBackButton: {
    width: 46,
    height: 46,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#677084",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  mapBackButtonText: {
    color: "#181d2c",
    fontSize: 26,
    lineHeight: 26,
    fontWeight: "500",
    marginTop: -2,
  },
  mapStatusPill: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "rgba(24,29,44,0.88)",
    alignItems: "center",
    justifyContent: "center",
  },
  mapStatusPillText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  mapCardsRow: {
    paddingRight: 24,
    gap: MAP_CARD_GAP,
  },
  mapLockerCard: {
    width: MAP_CARD_WIDTH,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.96)",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: "#657085",
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
  },
  mapLockerCardActive: {
    borderWidth: 1,
    borderColor: "rgba(223,76,60,0.22)",
    shadowOpacity: 0.24,
  },
  mapLockerDistanceBubble: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#1d2436",
    alignItems: "center",
    justifyContent: "center",
  },
  mapLockerDistanceValue: {
    color: "#ffffff",
    fontSize: 24,
    lineHeight: 25,
    fontWeight: "900",
  },
  mapLockerDistanceUnit: {
    color: "#a6adc2",
    fontSize: 11,
    textTransform: "uppercase",
    fontWeight: "700",
    marginTop: -1,
  },
  mapLockerMain: {
    flex: 1,
    gap: 4,
  },
  mapLockerName: {
    color: "#202435",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "900",
  },
  mapLockerMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  mapLockerAddress: {
    flex: 1,
    color: "#8f95a5",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  mapLockerSummary: {
    color: "#697183",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  mapInfoBanner: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 112,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#677084",
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  mapInfoBannerText: {
    color: "#202435",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  mapErrorBanner: {
    bottom: 182,
    backgroundColor: "rgba(228,77,60,0.95)",
  },
  mapErrorBannerText: {
    color: "#ffffff",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  mapMarker: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: "#131a2d",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0e1424",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  mapMarkerActive: {
    width: 58,
    height: 58,
    backgroundColor: "#df4c3c",
  },
  mapMarkerGlyph: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  mapMarkerGlyphHandleOne: {
    position: "absolute",
    width: 12,
    height: 3,
    borderRadius: 3,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
  },
  mapMarkerGlyphHandleTwo: {
    position: "absolute",
    width: 12,
    height: 3,
    borderRadius: 3,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "-45deg" }],
  },
  mapMarkerGlyphHandleInactive: {
    backgroundColor: "#f7f7f8",
  },
  locationPinGlyph: {
    width: 11,
    height: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  locationPinGlyphRing: {
    width: 9,
    height: 9,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#9ba2b2",
  },
  locationPinGlyphDot: {
    position: "absolute",
    bottom: 0,
    width: 3,
    height: 3,
    borderRadius: 999,
    backgroundColor: "#9ba2b2",
  },
  mapEmptyState: {
    marginHorizontal: 20,
    marginTop: 80,
    borderRadius: 32,
    backgroundColor: "#ffffff",
    padding: 24,
    shadowColor: "#657085",
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
  },
  mapEmptyTitle: {
    color: "#202435",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "900",
    marginBottom: 8,
  },
  mapEmptyText: {
    color: "#6f7685",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  mapFallbackSurface: {
    flex: 1,
    backgroundColor: "#f3efe4",
  },
  mapWebErrorCard: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 18,
    backgroundColor: "rgba(228,77,60,0.95)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: "#7d1f14",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  mapWebErrorTitle: {
    color: "#ffffff",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
    marginBottom: 4,
  },
  mapWebErrorText: {
    color: "rgba(255,255,255,0.95)",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  mapFallbackRoadOne: {
    position: "absolute",
    left: "-10%",
    right: "-10%",
    top: "16%",
    height: 2,
    backgroundColor: "rgba(198,167,98,0.55)",
    transform: [{ rotate: "6deg" }],
  },
  mapFallbackRoadTwo: {
    position: "absolute",
    left: "-4%",
    right: "-4%",
    top: "34%",
    height: 2,
    backgroundColor: "rgba(198,167,98,0.42)",
    transform: [{ rotate: "-8deg" }],
  },
  mapFallbackRoadThree: {
    position: "absolute",
    left: "14%",
    top: "-8%",
    bottom: "-8%",
    width: 2,
    backgroundColor: "rgba(198,167,98,0.48)",
    transform: [{ rotate: "8deg" }],
  },
  mapFallbackRoadFour: {
    position: "absolute",
    left: "48%",
    top: "-6%",
    bottom: "-6%",
    width: 2,
    backgroundColor: "rgba(198,167,98,0.35)",
    transform: [{ rotate: "-5deg" }],
  },
  mapFallbackRoadFive: {
    position: "absolute",
    left: "68%",
    top: "-10%",
    bottom: "-10%",
    width: 2,
    backgroundColor: "rgba(198,167,98,0.28)",
    transform: [{ rotate: "10deg" }],
  },
  mapFallbackRoadSix: {
    position: "absolute",
    left: "-6%",
    right: "-6%",
    bottom: "24%",
    height: 2,
    backgroundColor: "rgba(198,167,98,0.32)",
    transform: [{ rotate: "11deg" }],
  },
  mapFallbackCity: {
    position: "absolute",
    top: "45%",
    alignSelf: "center",
    color: "rgba(89,87,80,0.66)",
    fontSize: 32,
    fontWeight: "800",
  },
  mapFallbackUserDot: {
    position: "absolute",
    width: 18,
    height: 18,
    marginLeft: -9,
    marginTop: -9,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    borderWidth: 5,
    borderColor: "#11192d",
    shadowColor: "#11192d",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  mapFallbackMarkerWrap: {
    position: "absolute",
    marginLeft: -14,
    marginTop: -14,
  },
  mapFallbackMarkerWrapActive: {
    marginLeft: -29,
    marginTop: -29,
  },
  toolImage: {
    width: "88%",
    height: "88%",
  },
  toolArtFrame: {
    width: 130,
    height: 130,
    alignItems: "center",
    justifyContent: "center",
  },
  toolArtFrameCompact: {
    transform: [{ scale: 0.72 }],
  },
  drillShadow: {
    position: "absolute",
    bottom: 16,
    width: 70,
    height: 12,
    borderRadius: 999,
    backgroundColor: "rgba(53, 69, 102, 0.10)",
  },
  drillBody: {
    position: "absolute",
    top: 34,
    left: 30,
    width: 62,
    height: 38,
    borderRadius: 14,
    backgroundColor: "#2f3d52",
    transform: [{ rotate: "-18deg" }],
  },
  drillBodyCompact: {
    top: 38,
    left: 34,
  },
  drillNose: {
    position: "absolute",
    top: 42,
    right: 24,
    width: 38,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#78808c",
    transform: [{ rotate: "-18deg" }],
  },
  drillNoseCompact: {
    right: 28,
  },
  drillHandle: {
    position: "absolute",
    top: 64,
    left: 48,
    width: 20,
    height: 42,
    borderRadius: 10,
    backgroundColor: "#243348",
    transform: [{ rotate: "-12deg" }],
  },
  drillHandleCompact: {
    top: 67,
  },
  drillBattery: {
    position: "absolute",
    bottom: 26,
    left: 54,
    width: 26,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#2c394b",
  }
};
