import { StyleSheet } from "react-native";
import { MAP_CARD_GAP, MAP_CARD_WIDTH, palette } from "../theme";

export const styleChunk6 = {
  lockersListCard: {
    backgroundColor: palette.card,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: palette.border,
  },
  lockersListCardActive: {
    borderColor: palette.hero,
  },
  lockersMetaRow: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  mapStub: {
    backgroundColor: palette.text,
    borderRadius: 28,
    padding: 22,
    marginVertical: 8,
  },
  mapStubLabel: {
    color: "#f5d9ce",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontSize: 12,
    marginBottom: 8,
    fontWeight: "700",
  },
  mapStubText: {
    color: "#fffaf7",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    maxWidth: 280,
  },
  detailCard: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    padding: 20,
    shadowColor: "#9ba3b8",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  inlineLoader: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  detailHeader: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 14,
  },
  detailThumb: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: "#f0ddc7",
    justifyContent: "center",
    alignItems: "center",
  },
  detailThumbText: {
    fontSize: 20,
    fontWeight: "900",
    color: palette.heroDark,
  },
  detailMain: {
    flex: 1,
    justifyContent: "center",
  },
  detailTitle: {
    fontSize: 24,
    color: palette.text,
    fontWeight: "800",
    marginBottom: 6,
  },
  tagRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  tagChip: {
    borderRadius: 999,
    backgroundColor: palette.panel,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  tagChipActive: {
    backgroundColor: palette.text,
  },
  tagChipText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
  },
  tagChipTextActive: {
    color: "#fffaf7",
  },
  subsectionTitle: {
    fontSize: 15,
    color: palette.text,
    fontWeight: "800",
    marginBottom: 8,
    marginTop: 6,
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.text,
    marginBottom: 8,
  },
  primaryButton: {
    marginTop: 18,
    backgroundColor: palette.hero,
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fffaf7",
    fontSize: 15,
    fontWeight: "800",
  },
  secondaryButton: {
    marginTop: 12,
    backgroundColor: palette.text,
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#fffaf7",
    fontSize: 15,
    fontWeight: "800",
  },
  ghostButton: {
    marginTop: 12,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: palette.panel,
  },
  ghostButtonText: {
    color: palette.text,
    fontWeight: "800",
  },
  ghostButtonDark: {
    marginTop: 18,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: palette.text,
  },
  ghostButtonDarkText: {
    color: "#fffaf7",
    fontWeight: "800",
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  checkoutHero: {
    backgroundColor: palette.hero,
    borderRadius: 26,
    padding: 18,
    shadowColor: "#c53f34",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  checkoutHeroTitle: {
    fontSize: 22,
    color: "#fffaf7",
    fontWeight: "800",
    marginBottom: 8,
  },
  checkoutHeroText: {
    color: "#ffd9d1",
    lineHeight: 20,
  },
  checkoutCard: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    padding: 20,
    shadowColor: "#9ba3b8",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  checkoutDivider: {
    height: 1,
    backgroundColor: palette.border,
    marginVertical: 16,
  },
  checkoutRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  checkoutStrong: {
    color: palette.text,
    fontWeight: "800",
  },
  bookingActions: {
    marginTop: 4,
  },
  inlineNotice: {
    marginTop: 12,
    borderRadius: 16,
    backgroundColor: "#fde5cf",
    padding: 14,
  },
  profileCard: {
    backgroundColor: "#ffffff",
    borderRadius: 26,
    padding: 20,
    shadowColor: "#9ba3b8",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  profileMeta: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  bottomNav: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 22,
    backgroundColor: "#ffffff",
    borderRadius: 28,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    shadowColor: "#8d97ab",
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    minHeight: 62,
  },
  navItemActive: {
    backgroundColor: "transparent",
  },
  navItemText: {
    color: "#a6a9b2",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 6,
  },
  navItemTextActive: {
    color: "#df4c3c",
  },
  navIconWrap: {
    width: 28,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  navGlyphFillInactive: {
    backgroundColor: "#aeb1bc",
  },
  navGlyphFillActive: {
    backgroundColor: "#e53a32",
  },
  navGlyphStrokeInactive: {
    borderColor: "#aeb1bc",
  },
  navGlyphStrokeActive: {
    borderColor: "#e53a32",
  },
  navHomeGlyph: {
    width: 20,
    height: 18,
    alignItems: "center",
  },
  navHomeRoof: {
    width: 14,
    height: 14,
    transform: [{ rotate: "45deg" }],
    borderTopLeftRadius: 3,
    marginTop: 1,
  },
  navHomeBody: {
    position: "absolute",
    bottom: 0,
    width: 12,
    height: 9,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  navHomeDoor: {
    position: "absolute",
    bottom: 0,
    width: 4,
    height: 5,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    backgroundColor: "#ffffff",
    opacity: 0,
  },
  navHomeDoorActive: {
    opacity: 1,
  },
  navMapGlyph: {
    width: 18,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  navMapPin: {
    width: 14,
    height: 14,
    borderRadius: 999,
    borderWidth: 2,
    backgroundColor: "transparent",
  },
  navMapPinDot: {
    position: "absolute",
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#aeb1bc",
  },
  navMapPinDotActive: {
    backgroundColor: "#e53a32",
  },
  navMapBase: {
    position: "absolute",
    bottom: 1,
    width: 4,
    height: 7,
    borderRadius: 2,
    backgroundColor: "#aeb1bc",
  },
  navCatalogGlyph: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  navCatalogHandleLeft: {
    position: "absolute",
    width: 13,
    height: 2,
    borderRadius: 2,
    transform: [{ rotate: "45deg" }],
  },
  navCatalogHeadLeft: {
    position: "absolute",
    width: 4,
    height: 7,
    borderRadius: 2,
    transform: [{ rotate: "45deg" }],
    top: 4,
    right: 4,
  },
  navCatalogHandleRight: {
    position: "absolute",
    width: 13,
    height: 2,
    borderRadius: 2,
    transform: [{ rotate: "-45deg" }],
  },
  navCatalogHeadRight: {
    position: "absolute",
    width: 6,
    height: 6,
    borderRadius: 2,
    borderWidth: 2,
    backgroundColor: "transparent",
    top: 4,
    left: 4,
    transform: [{ rotate: "-45deg" }],
  },
  navBookingGlyph: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  navBookingCircle: {
    position: "absolute",
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 2,
    backgroundColor: "transparent",
  },
  navBookingHandShort: {
    position: "absolute",
    width: 2,
    height: 4,
    borderRadius: 2,
    top: 5,
  },
  navBookingHandLong: {
    position: "absolute",
    width: 5,
    height: 2,
    borderRadius: 2,
    left: 9,
    top: 10,
  },
  navMoreGlyph: {
    flexDirection: "column",
    gap: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  navMoreDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#aeb1bc",
  },
  navMoreDotActive: {
    backgroundColor: "#e53a32",
  },
  navBadge: {
    position: "absolute",
    top: -5,
    right: -10,
    minWidth: 16,
    height: 16,
    borderRadius: 999,
    backgroundColor: "#df4c3c",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  navBadgeText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  loadingShell: {
    flex: 1,
    backgroundColor: palette.bg,
    justifyContent: "center",
    padding: 24,
  },
  loadingCard: {
    backgroundColor: palette.card,
    borderRadius: 30,
    padding: 28,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    gap: 12,
  },
  loadingTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: palette.text,
  },
  loadingText: {
    fontSize: 15,
    lineHeight: 21,
    color: palette.subtext,
    textAlign: "center",
  }
};
