import { StyleSheet } from "react-native";
import { MAP_CARD_GAP, MAP_CARD_WIDTH, palette } from "../theme";

export const styleChunk5 = {
  drillBatteryCompact: {
    bottom: 30,
  },
  drillAccent: {
    position: "absolute",
    top: 44,
    left: 42,
    width: 36,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#4ba2c6",
    transform: [{ rotate: "-18deg" }],
  },
  generatorShadow: {
    position: "absolute",
    bottom: 12,
    width: 74,
    height: 12,
    borderRadius: 999,
    backgroundColor: "rgba(161, 100, 62, 0.12)",
  },
  generatorShell: {
    width: 86,
    height: 70,
    borderRadius: 22,
    backgroundColor: "#ef6f34",
    justifyContent: "center",
    alignItems: "center",
  },
  generatorShellCompact: {
    transform: [{ scale: 0.94 }],
  },
  generatorVent: {
    position: "absolute",
    left: 14,
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 4,
    borderColor: "#3c4048",
  },
  generatorPanel: {
    position: "absolute",
    right: 16,
    width: 18,
    height: 24,
    borderRadius: 6,
    backgroundColor: "#444a55",
  },
  generatorHandle: {
    position: "absolute",
    top: -10,
    width: 36,
    height: 18,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderWidth: 5,
    borderBottomWidth: 0,
    borderColor: "#ef6f34",
  },
  generatorWheelLeft: {
    position: "absolute",
    bottom: 18,
    left: 30,
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: "#30343d",
  },
  generatorWheelRight: {
    position: "absolute",
    bottom: 18,
    right: 30,
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: "#30343d",
  },
  welderShadow: {
    position: "absolute",
    bottom: 12,
    width: 74,
    height: 12,
    borderRadius: 999,
    backgroundColor: "rgba(128, 126, 64, 0.14)",
  },
  welderBody: {
    width: 78,
    height: 58,
    borderRadius: 14,
    backgroundColor: "#e5c54f",
    transform: [{ rotate: "-6deg" }],
    alignItems: "center",
    justifyContent: "center",
  },
  welderBodyCompact: {
    transform: [{ rotate: "-6deg" }, { scale: 0.96 }],
  },
  welderPanel: {
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: "#51565f",
  },
  welderHandle: {
    position: "absolute",
    top: 34,
    left: 24,
    width: 18,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#3d4248",
    transform: [{ rotate: "-30deg" }],
  },
  welderCable: {
    position: "absolute",
    right: 22,
    bottom: 34,
    width: 34,
    height: 22,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderColor: "#3b4048",
    borderBottomRightRadius: 20,
  },
  toolboxShadow: {
    position: "absolute",
    bottom: 16,
    width: 68,
    height: 12,
    borderRadius: 999,
    backgroundColor: "rgba(67, 75, 96, 0.12)",
  },
  toolboxBody: {
    width: 78,
    height: 50,
    borderRadius: 16,
    backgroundColor: "#49546a",
  },
  toolboxBodyCompact: {
    transform: [{ scale: 0.95 }],
  },
  toolboxHandle: {
    position: "absolute",
    top: 32,
    width: 28,
    height: 16,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderWidth: 4,
    borderBottomWidth: 0,
    borderColor: "#49546a",
  },
  toolboxLatchLeft: {
    position: "absolute",
    top: 62,
    left: 38,
    width: 8,
    height: 10,
    borderRadius: 4,
    backgroundColor: "#f0c650",
  },
  toolboxLatchRight: {
    position: "absolute",
    top: 62,
    right: 38,
    width: 8,
    height: 10,
    borderRadius: 4,
    backgroundColor: "#f0c650",
  },
  heroCard: {
    borderRadius: 30,
    padding: 22,
    backgroundColor: "#1f2330",
    shadowColor: "#161a25",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  heroGlowOne: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: "rgba(255,255,255,0.10)",
    top: -70,
    right: -40,
  },
  heroGlowTwo: {
    position: "absolute",
    width: 160,
    height: 160,
    borderRadius: 160,
    backgroundColor: "rgba(255,255,255,0.08)",
    bottom: -50,
    left: -20,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 10,
  },
  heroBrandPill: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroBrandPillText: {
    color: "#f3f4f7",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroStatusPillApproved: {
    backgroundColor: "rgba(108, 199, 145, 0.16)",
  },
  heroStatusPillPending: {
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  heroStatusPillText: {
    color: "#f3f4f7",
    fontSize: 12,
    fontWeight: "800",
  },
  heroBody: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  heroCopyBlock: {
    flex: 1,
    paddingRight: 2,
  },
  heroKicker: {
    color: "#8f96a9",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    fontSize: 11,
    marginBottom: 10,
    fontWeight: "800",
  },
  heroTitle: {
    color: "#ffffff",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "900",
    marginBottom: 10,
  },
  heroText: {
    color: "#c6cbd8",
    fontSize: 14,
    lineHeight: 20,
  },
  heroVisualCard: {
    width: 136,
    borderRadius: 22,
    backgroundColor: "#2a3040",
    padding: 12,
    justifyContent: "space-between",
  },
  heroVisualLabel: {
    color: "#8f96a9",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  heroVisualArtwork: {
    height: 88,
    borderRadius: 18,
    backgroundColor: "#fff6f2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  heroVisualTitle: {
    color: "#ffffff",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
    marginBottom: 6,
  },
  heroVisualPrice: {
    color: "#c6cbd8",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  heroMetaRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  heroMetaCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "#2a3040",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  heroMetaLabel: {
    color: "#8f96a9",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "800",
    marginBottom: 6,
  },
  heroMetaValue: {
    color: "#ffffff",
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "900",
  },
  heroMessageCard: {
    marginTop: 12,
    borderRadius: 18,
    backgroundColor: "#2a3040",
    padding: 14,
  },
  heroMessageLabel: {
    color: "#8f96a9",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "800",
    marginBottom: 6,
  },
  heroMessageText: {
    color: "#f3f4f7",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  heroActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  heroAction: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
  },
  heroActionPrimary: {
    backgroundColor: "#fffaf7",
  },
  heroActionGhost: {
    backgroundColor: "#2a3040",
  },
  heroActionPrimaryText: {
    color: "#1f2330",
    fontWeight: "800",
  },
  heroActionGhostText: {
    color: "#f3f4f7",
    fontWeight: "700",
  },
  alertWarn: {
    backgroundColor: "#fde5cf",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  alertDanger: {
    backgroundColor: "#fde0da",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  alertTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 6,
  },
  alertText: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    color: palette.text,
    fontWeight: "800",
  },
  sectionHint: {
    color: palette.subtext,
    fontSize: 12,
    maxWidth: 160,
    textAlign: "right",
  },
  sectionAction: {
    fontSize: 12,
    color: palette.hero,
    fontWeight: "700",
  },
  cityRow: {
    gap: 10,
    paddingBottom: 18,
  },
  cityChip: {
    borderRadius: 999,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cityChipActive: {
    backgroundColor: palette.text,
    borderColor: palette.text,
  },
  cityChipText: {
    color: palette.text,
    fontWeight: "700",
  },
  cityChipTextActive: {
    color: "#fffaf7",
  },
  loadingInlineCard: {
    borderRadius: 20,
    backgroundColor: palette.panel,
    padding: 16,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  tabBlock: {
    gap: 18,
  },
  lockerCard: {
    backgroundColor: palette.card,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
  },
  lockerCardActive: {
    borderColor: palette.hero,
    shadowColor: palette.hero,
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  lockerCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 17,
    color: palette.text,
    fontWeight: "800",
    marginBottom: 4,
  },
  cardText: {
    fontSize: 14,
    lineHeight: 19,
    color: palette.subtext,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusGood: {
    backgroundColor: "#dff2e5",
  },
  statusWarn: {
    backgroundColor: "#fde5cf",
  },
  statusText: {
    fontSize: 12,
    fontWeight: "700",
    color: palette.text,
  },
  lockerStats: {
    flexDirection: "row",
    gap: 10,
  },
  metric: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: palette.panel,
    padding: 12,
  },
  metricLabel: {
    fontSize: 11,
    color: palette.subtext,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  metricValue: {
    color: palette.text,
    fontWeight: "800",
    fontSize: 15,
  },
  availabilityRow: {
    gap: 10,
  },
  availabilityCard: {
    backgroundColor: palette.panel,
    borderRadius: 20,
    padding: 16,
  },
  availabilityCardWide: {
    backgroundColor: palette.card,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: palette.border,
  },
  productCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 16,
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
    shadowColor: "#9ba3b8",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  productCardActive: {
    shadowOpacity: 0.2,
    shadowRadius: 22,
  },
  productThumb: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#f2d9be",
    justifyContent: "center",
    alignItems: "center",
  },
  productThumbText: {
    fontSize: 18,
    fontWeight: "900",
    color: palette.heroDark,
  },
  productMain: {
    flex: 1,
  },
  productMeta: {
    alignItems: "flex-end",
    gap: 4,
  },
  priceText: {
    fontSize: 15,
    fontWeight: "800",
    color: palette.text,
  },
  stockText: {
    fontSize: 12,
    color: palette.subtext,
    fontWeight: "700",
  }
};
