import { StyleSheet } from "react-native";
import { MAP_CARD_GAP, MAP_CARD_WIDTH, palette } from "../theme";

export const styleChunk3 = {
  inputLabel: {
    fontSize: 13,
    color: palette.subtext,
    fontWeight: "700",
    marginTop: 18,
    marginBottom: 8,
  },
  authInputShell: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: 6,
  },
  authInputPrefix: {
    minWidth: 58,
    borderRadius: 16,
    backgroundColor: "#f1e2d4",
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  authInputPrefixText: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  authTextInput: {
    flex: 1,
    paddingRight: 14,
    paddingVertical: 14,
    fontSize: 16,
    color: palette.text,
  },
  authInfoStrip: {
    marginTop: 12,
    borderRadius: 18,
    backgroundColor: "#f6ede4",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  authInfoStripText: {
    color: palette.subtext,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  authPrimaryPressable: {
    marginTop: 16,
  },
  authBackLink: {
    marginTop: 12,
    alignItems: "center",
  },
  authBackLinkText: {
    color: palette.subtext,
    fontSize: 14,
    fontWeight: "700",
  },
  authPrimaryButton: {
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  authPrimaryButtonText: {
    color: "#fffaf7",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  authSecondaryButton: {
    marginTop: 12,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: palette.border,
  },
  authSecondaryButtonText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  otpPreviewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  otpBox: {
    flex: 1,
    height: 68,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    alignItems: "center",
    justifyContent: "center",
  },
  otpBoxFilled: {
    borderColor: palette.hero,
    backgroundColor: "#fff4f1",
  },
  otpBoxText: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
  },
  hiddenOtpInput: {
    position: "absolute",
    opacity: 0,
    pointerEvents: "none",
  },
  devHint: {
    marginTop: 14,
    borderRadius: 20,
    backgroundColor: "#fce7d8",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  devHintLabel: {
    fontSize: 12,
    color: palette.subtext,
    marginBottom: 2,
    fontWeight: "700",
  },
  devHintCaption: {
    fontSize: 12,
    color: palette.subtext,
  },
  devHintValue: {
    fontSize: 24,
    color: palette.heroDark,
    fontWeight: "900",
    letterSpacing: 2,
  },
  authErrorCard: {
    marginTop: 14,
    borderRadius: 20,
    backgroundColor: "#fde0da",
    padding: 14,
  },
  authFeatureRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  miniFeature: {
    width: 228,
    borderRadius: 24,
    backgroundColor: "#f3e6d8",
    padding: 18,
  },
  miniFeatureClay: {
    backgroundColor: "#edd8cb",
  },
  miniFeatureDark: {
    backgroundColor: "#202435",
  },
  miniFeatureEyebrow: {
    fontSize: 11,
    lineHeight: 14,
    color: "#9f5c43",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  miniFeatureEyebrowDark: {
    color: "#ffcec5",
  },
  miniFeatureTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: palette.text,
    fontWeight: "800",
    marginBottom: 8,
  },
  miniFeatureTitleDark: {
    color: "#fffaf7",
  },
  miniFeatureText: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.subtext,
  },
  miniFeatureTextDark: {
    color: "#d5d8e2",
  },
  authTrustPanel: {
    marginTop: 18,
    borderRadius: 30,
    backgroundColor: palette.card,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.border,
  },
  authTrustTitle: {
    color: palette.text,
    fontSize: 19,
    fontWeight: "800",
    marginBottom: 14,
  },
  authTrustGrid: {
    gap: 10,
  },
  authTrustItem: {
    borderRadius: 20,
    backgroundColor: palette.panel,
    padding: 14,
  },
  authTrustItemTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  authTrustItemText: {
    color: palette.subtext,
    fontSize: 13,
    lineHeight: 18,
  },
  demoButton: {
    marginTop: 16,
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: "center",
    backgroundColor: "#efe3d6",
  },
  demoButtonText: {
    color: palette.text,
    fontWeight: "800",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  eyebrow: {
    fontSize: 12,
    color: palette.subtext,
    textTransform: "uppercase",
    letterSpacing: 1.4,
    marginBottom: 6,
  },
  headerTitle: {
    fontSize: 28,
    lineHeight: 30,
    color: palette.text,
    fontWeight: "800",
    maxWidth: 220,
  },
  modeBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  modeBadgeLive: {
    backgroundColor: "#dbf4e3",
  },
  modeBadgeFallback: {
    backgroundColor: "#fde5cf",
  },
  modeBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: palette.text,
  },
  nonHomeMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  nonHomeMetaText: {
    flex: 1,
    textAlign: "right",
    marginLeft: 10,
    color: "#9ca2b0",
    fontSize: 12,
    fontWeight: "700",
  },
  homeTopBar: {
    paddingTop: 6,
    marginBottom: 12,
  },
  homeUserRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  homeUserInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  homeAvatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: "#efe4d7",
    marginRight: 14,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  homeAvatarInitials: {
    color: "#7f5539",
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "900",
  },
  homeUserTextBlock: {
    flex: 1,
    justifyContent: "center",
    gap: 4,
  },
  homeUserName: {
    fontSize: 19,
    lineHeight: 23,
    color: "#202435",
    fontWeight: "900",
  },
  homeUserBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pointsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "#ea2d2d",
  },
  diamondGlyph: {
    width: 8,
    height: 8,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
    borderRadius: 2,
  },
  pointsBadgeText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  homeCityText: {
    color: "#9ea2ad",
    fontSize: 12,
    fontWeight: "700",
  },
  homeUtilityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  utilityIconButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "#f6f6f7",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  utilityDot: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#e14636",
  },
  supportGlyph: {
    width: 18,
    height: 18,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  supportGlyphBand: {
    position: "absolute",
    top: 1,
    width: 14,
    height: 8,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: "#25293a",
  },
  supportGlyphLeft: {
    position: "absolute",
    left: 1,
    top: 8,
    width: 4,
    height: 6,
    borderBottomLeftRadius: 4,
    borderTopLeftRadius: 3,
    borderWidth: 2,
    borderRightWidth: 0,
    borderColor: "#25293a",
  },
  supportGlyphRight: {
    position: "absolute",
    right: 1,
    top: 8,
    width: 4,
    height: 6,
    borderBottomRightRadius: 4,
    borderTopRightRadius: 3,
    borderWidth: 2,
    borderLeftWidth: 0,
    borderColor: "#25293a",
  },
  supportGlyphMic: {
    position: "absolute",
    right: 2,
    bottom: 1,
    width: 6,
    height: 2,
    borderRadius: 2,
    backgroundColor: "#25293a",
  },
  bellGlyph: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "flex-end",
    position: "relative",
  },
  bellGlyphBody: {
    width: 12,
    height: 12,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    borderWidth: 2,
    borderColor: "#25293a",
    borderBottomWidth: 1.5,
  },
  bellGlyphClapper: {
    width: 6,
    height: 2,
    borderRadius: 2,
    backgroundColor: "#25293a",
    marginTop: 2,
  },
  homeSearchBar: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: "#f4f4f5",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 12,
  },
  homeSearchText: {
    color: "#b8bbc4",
    fontSize: 18,
    fontWeight: "600",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 124,
  },
  homeScrollContent: {
    paddingTop: 8,
    paddingBottom: 136,
  },
  homeSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  homeSectionTitle: {
    fontSize: 17,
    lineHeight: 21,
    color: "#202435",
    fontWeight: "900",
  },
  homeSectionAction: {
    fontSize: 14,
    lineHeight: 18,
    color: "#b4b6be",
    fontWeight: "700",
  },
  homeTabBlock: {
    gap: 26,
  },
  homeIdeasRow: {
    gap: 12,
    paddingRight: 20,
  },
  featuredToolsRow: {
    gap: 14,
    paddingRight: 20,
  },
  featuredToolCard: {
    width: 176,
    borderRadius: 22,
    backgroundColor: "#ffffff",
    padding: 12,
    shadowColor: "#adb3c3",
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  featuredToolArtwork: {
    height: 190,
    borderRadius: 18,
    backgroundColor: "#f6f6f7",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 12,
  },
  featuredToolTitle: {
    fontSize: 16,
    lineHeight: 21,
    color: "#202435",
    fontWeight: "800",
    minHeight: 64,
    marginHorizontal: 2,
    marginBottom: 10,
  },
  featuredToolPricePill: {
    alignSelf: "flex-start",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "#ef2b2d",
  },
  featuredToolPriceText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  homeLockerRow: {
    gap: 12,
    paddingRight: 20,
  },
  homeLockerCard: {
    width: 280,
    borderRadius: 22,
    backgroundColor: "#ffffff",
    padding: 16,
    shadowColor: "#9ba3b8",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  homeLockerCardActive: {
    borderWidth: 1,
    borderColor: "rgba(223,76,60,0.20)",
    shadowOpacity: 0.2,
  },
  homeLockerCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  }
};
