import { StyleSheet } from "react-native";
import { MAP_CARD_GAP, MAP_CARD_WIDTH, palette } from "../theme";

export const styleChunk1 = {
  safe: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  safeHome: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  appShell: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  appShellHome: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  welcomeShell: {
    flexGrow: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 28,
    paddingTop: 26,
    paddingBottom: 28,
    justifyContent: "space-between",
  },
  welcomeTopBlock: {
    alignItems: "center",
    paddingTop: 34,
  },
  welcomeCarousel: {
    width: "100%",
  },
  welcomeCarouselContent: {
    alignItems: "stretch",
  },
  welcomeSlide: {
    alignItems: "center",
  },
  welcomeIllustrationWrap: {
    width: "100%",
    alignItems: "center",
    marginBottom: 26,
  },
  depositArt: {
    width: 238,
    height: 238,
    alignItems: "center",
    justifyContent: "center",
  },
  depositArtShadow: {
    position: "absolute",
    width: 132,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(211, 51, 42, 0.10)",
    bottom: 18,
  },
  depositRing: {
    position: "absolute",
    width: 160,
    height: 160,
    borderRadius: 999,
    borderWidth: 18,
    borderColor: "#e5574e",
    backgroundColor: "#ffffff",
    shadowColor: "#b6342b",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  depositRingSlash: {
    position: "absolute",
    width: 114,
    height: 18,
    borderRadius: 999,
    backgroundColor: "#de4b42",
    top: 54,
    left: 18,
    transform: [{ rotate: "-25deg" }],
  },
  depositBill: {
    position: "absolute",
    width: 88,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#a6edff",
    borderWidth: 3,
    borderColor: "#5dbedf",
    padding: 10,
    shadowColor: "#60cde4",
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  depositBillFront: {
    left: 32,
    top: 78,
    transform: [{ rotate: "-13deg" }],
  },
  depositBillBack: {
    right: 42,
    top: 102,
    transform: [{ rotate: "18deg" }],
  },
  depositBillCorner: {
    position: "absolute",
    width: 18,
    height: 18,
    borderBottomRightRadius: 14,
    backgroundColor: "#d9f8ff",
    top: 0,
    left: 0,
  },
  depositBillCircle: {
    width: 38,
    height: 26,
    borderRadius: 999,
    backgroundColor: "#7fd7f5",
    alignSelf: "center",
    marginTop: 9,
  },
  depositCoin: {
    position: "absolute",
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "#f3cc75",
    borderWidth: 3,
    borderColor: "#d9b45a",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#cda54c",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  depositCoinTop: {
    top: 64,
    right: 56,
  },
  depositCoinRight: {
    top: 122,
    right: 34,
  },
  depositCoinInner: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#ddb962",
  },
  nearbyArt: {
    width: 238,
    height: 238,
    alignItems: "center",
    justifyContent: "center",
  },
  nearbyArtShadow: {
    position: "absolute",
    width: 132,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(60, 181, 220, 0.10)",
    bottom: 20,
  },
  nearbyMapCard: {
    position: "absolute",
    width: 154,
    height: 112,
    borderRadius: 28,
    backgroundColor: "#ebfbff",
    borderWidth: 3,
    borderColor: "#9de7fb",
    transform: [{ rotate: "-10deg" }],
  },
  nearbyMapRoadHorizontal: {
    position: "absolute",
    height: 12,
    left: 12,
    right: 12,
    top: 46,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  nearbyMapRoadVertical: {
    position: "absolute",
    width: 12,
    top: 10,
    bottom: 10,
    left: 66,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  nearbyMapDot: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: "#ff8f87",
    right: 30,
    top: 28,
  },
  nearbyPin: {
    position: "absolute",
    left: 38,
    top: 42,
    width: 54,
    height: 70,
    borderTopLeftRadius: 27,
    borderTopRightRadius: 27,
    borderBottomLeftRadius: 27,
    borderBottomRightRadius: 8,
    backgroundColor: "#e54f44",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-35deg" }],
    zIndex: 2,
  },
  nearbyPinInner: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  nearbyLocker: {
    position: "absolute",
    right: 46,
    top: 72,
    width: 86,
    height: 104,
    borderRadius: 20,
    backgroundColor: "#8ee3fb",
    borderWidth: 3,
    borderColor: "#58bfdf",
    padding: 10,
    zIndex: 2,
  },
  nearbyLockerHeader: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#e9fbff",
    marginBottom: 10,
  },
  nearbyLockerGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  nearbyLockerCell: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: "#d9f8ff",
  },
  fastArt: {
    width: 238,
    height: 238,
    alignItems: "center",
    justifyContent: "center",
  },
  fastArtShadow: {
    position: "absolute",
    width: 132,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(221, 54, 45, 0.10)",
    bottom: 22,
  },
  fastPhone: {
    width: 118,
    height: 176,
    borderRadius: 28,
    backgroundColor: "#fefefe",
    borderWidth: 6,
    borderColor: "#ee5c54",
    padding: 10,
    shadowColor: "#d9483f",
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  fastPhoneTop: {
    width: 46,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#f3c1be",
    alignSelf: "center",
    marginBottom: 12,
  },
  fastPhoneScreen: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "#fff4f3",
    padding: 12,
  },
  fastPhoneLineShort: {
    width: "45%",
    height: 10,
    borderRadius: 999,
    backgroundColor: "#f4b8b5",
    marginBottom: 8,
  },
  fastPhoneLineLong: {
    width: "80%",
    height: 10,
    borderRadius: 999,
    backgroundColor: "#f8d6d3",
    marginBottom: 12,
  },
  fastPhonePill: {
    width: "100%",
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ea8d87",
    marginTop: 10,
  },
  fastCheckBubble: {
    position: "absolute",
    right: 36,
    top: 64,
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: "#8ee3a5",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#6cc886",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  fastCheckMarkLeft: {
    position: "absolute",
    width: 12,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    left: 16,
    top: 30,
    transform: [{ rotate: "45deg" }],
  },
  fastCheckMarkRight: {
    position: "absolute",
    width: 22,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    right: 12,
    top: 24,
    transform: [{ rotate: "-45deg" }],
  },
  fastSpeedLineOne: {
    position: "absolute",
    left: 32,
    top: 92,
    width: 42,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#ffd0cd",
  },
  fastSpeedLineTwo: {
    position: "absolute",
    left: 26,
    top: 114,
    width: 58,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#ffdede",
  },
  returnArt: {
    width: 238,
    height: 238,
    alignItems: "center",
    justifyContent: "center",
  },
  returnArtShadow: {
    position: "absolute",
    width: 132,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(80, 160, 220, 0.08)",
    bottom: 18,
  },
  returnCircle: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: 999,
    borderWidth: 12,
    borderColor: "#db4137",
    opacity: 0.18,
  },
  returnArrowTop: {
    position: "absolute",
    width: 24,
    height: 24,
    borderTopWidth: 8,
    borderRightWidth: 8,
    borderColor: "#db4137",
    right: 10,
    top: 20,
    transform: [{ rotate: "20deg" }],
  },
  returnArrowBottom: {
    position: "absolute",
    width: 24,
    height: 24,
    borderBottomWidth: 8,
    borderLeftWidth: 8,
    borderColor: "#db4137",
    left: 10,
    bottom: 20,
    transform: [{ rotate: "20deg" }],
  },
  returnLocker: {
    position: "absolute",
    right: 42,
    top: 74,
    width: 82,
    height: 98,
    borderRadius: 20,
    backgroundColor: "#a7edff",
    borderWidth: 3,
    borderColor: "#59bfdf",
    alignItems: "center",
    justifyContent: "center",
  },
  returnLockerDoor: {
    width: 50,
    height: 66,
    borderRadius: 14,
    backgroundColor: "#dffaff",
    borderWidth: 2,
    borderColor: "#93def4",
  },
  returnBox: {
    position: "absolute",
    left: 46,
    top: 120,
    width: 68,
    height: 54,
    borderRadius: 14,
    backgroundColor: "#ffd78f",
    borderWidth: 3,
    borderColor: "#e5b95d",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 12,
  },
  returnBoxTop: {
    width: 48,
    height: 12,
    borderRadius: 8,
    backgroundColor: "#ffe9bc",
  },
  welcomeDotsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 22,
    position: "relative",
  },
  welcomeDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#f6d5d5",
  },
  welcomeDotActive: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#da362d",
  },
  welcomeTitle: {
    fontSize: 28,
    lineHeight: 34,
    color: "#171d2e",
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 10,
    maxWidth: 320,
  },
  welcomeSubtitle: {
    fontSize: 16,
    lineHeight: 22,
    color: "#a8aebb",
    textAlign: "center",
    maxWidth: 310,
    marginBottom: 18,
  },
  welcomeLinkWrap: {
    paddingVertical: 8,
  },
  welcomeLink: {
    fontSize: 18,
    lineHeight: 22,
    color: "#df4035",
    fontWeight: "700",
  },
  welcomeButtonsBlock: {
    gap: 14,
  },
  welcomePrimaryButton: {
    borderRadius: 18,
    backgroundColor: "#dd362d",
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ca342b",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  welcomePrimaryButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  welcomeSecondaryButton: {
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#ee4b40",
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  welcomeSecondaryButtonText: {
    color: "#df4035",
    fontSize: 18,
    fontWeight: "700",
  },
  entryShell: {
    flexGrow: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 26,
    paddingTop: 34,
    paddingBottom: 22,
    justifyContent: "space-between",
  },
  entryCenteredArea: {
    flex: 1,
    justifyContent: "center",
  },
  entryConfirmShell: {
    flexGrow: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 26,
    paddingTop: 20,
    paddingBottom: 34,
  },
  entryConfirmScreen: {
    flex: 1,
    minHeight: "100%",
  },
  entryConfirmBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 40,
  },
  entryTitleBlock: {
    alignItems: "center",
    marginBottom: 34,
  },
  entryConfirmTitleBlock: {
    alignItems: "center",
    marginBottom: 46,
  },
  entryTitle: {
    fontSize: 28,
    lineHeight: 34,
    color: "#151b2e",
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 8,
  },
  entrySubtitle: {
    fontSize: 15,
    lineHeight: 21,
    color: "#b1b5c1",
    textAlign: "center",
    maxWidth: 280,
  },
  entrySubtitleStrong: {
    color: "#151b2e",
    fontWeight: "800",
  }
};
