import { StyleSheet } from "react-native";
import { MAP_CARD_GAP, MAP_CARD_WIDTH, palette } from "../theme";

export const styleChunk2 = {
  softInputShell: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: "#f5f5f6",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    marginBottom: 18,
  },
  softInputIconWrap: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  softInputText: {
    flex: 1,
    fontSize: 17,
    color: "#7e8594",
    fontWeight: "500",
  },
  entrySupportText: {
    fontSize: 13,
    lineHeight: 18,
    color: "#b1b5c1",
    textAlign: "center",
    marginTop: -6,
    marginBottom: 18,
    paddingHorizontal: 10,
  },
  softInputPlaceholder: {
    color: "#bfc3cd",
  },
  softPrimaryButton: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: "#dd362d",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ca342b",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  softPrimaryButtonDisabled: {
    backgroundColor: "#f2a8a4",
    shadowOpacity: 0,
  },
  softPrimaryButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  entrySwitchBlock: {
    alignItems: "center",
    marginTop: 34,
    gap: 8,
  },
  entrySwitchText: {
    color: "#b1b5c1",
    fontSize: 15,
    fontWeight: "600",
  },
  entrySwitchLink: {
    color: "#e53e33",
    fontSize: 17,
    fontWeight: "800",
  },
  entryBackButton: {
    marginTop: 18,
    alignItems: "center",
  },
  entryIconBackButton: {
    width: 44,
    height: 44,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  entryIconBackText: {
    color: "#151b2e",
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "600",
  },
  entryBackButtonText: {
    color: "#b1b5c1",
    fontSize: 15,
    fontWeight: "700",
  },
  entryLegalText: {
    fontSize: 13,
    lineHeight: 18,
    color: "#a7acb8",
    textAlign: "center",
    paddingHorizontal: 18,
  },
  entryLegalLink: {
    color: "#dd362d",
    fontWeight: "800",
    textDecorationLine: "underline",
  },
  policyOverlay: {
    flex: 1,
    backgroundColor: "rgba(20, 28, 46, 0.45)",
    justifyContent: "flex-end",
  },
  policySheet: {
    maxHeight: "88%",
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  policyHandle: {
    width: 44,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d9dce3",
    alignSelf: "center",
    marginBottom: 12,
  },
  policyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 10,
  },
  policyTitle: {
    flex: 1,
    color: "#151b2e",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
  },
  policyHeaderClose: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "#f4f5f8",
  },
  policyHeaderCloseText: {
    color: "#4c5569",
    fontSize: 13,
    fontWeight: "700",
  },
  policyScroll: {
    flex: 1,
  },
  policyScrollContent: {
    paddingBottom: 14,
  },
  policyUpdatedAt: {
    color: "#9aa2b3",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 10,
  },
  policySectionTitle: {
    color: "#1a2238",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 8,
    marginBottom: 6,
  },
  policyParagraph: {
    color: "#5f687d",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  policyBullet: {
    color: "#5f687d",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  policyConfirmButton: {
    marginTop: 10,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#dd362d",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ca342b",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  policyConfirmButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  entryDemoLink: {
    marginTop: 10,
    alignItems: "center",
  },
  entryDemoLinkText: {
    color: "#dd4338",
    fontSize: 15,
    fontWeight: "700",
  },
  entryOtpRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginBottom: 24,
  },
  entryOtpBox: {
    width: 66,
    height: 66,
    borderRadius: 20,
    backgroundColor: "#f5f5f6",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  entryOtpBoxActive: {
    borderColor: "#ef9993",
    backgroundColor: "#fff8f7",
  },
  entryOtpBoxFilled: {
    backgroundColor: "#fff3f2",
    borderColor: "#ef9993",
  },
  entryOtpBoxText: {
    color: "#1a2032",
    fontSize: 24,
    fontWeight: "800",
  },
  entryHintCard: {
    borderRadius: 18,
    backgroundColor: "#f8f4f4",
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 18,
    alignItems: "center",
  },
  entryHintLabel: {
    color: "#9ea4b2",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  entryHintValue: {
    color: "#de4137",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 3,
  },
  entryTimerText: {
    color: "#b1b5c1",
    fontSize: 16,
    lineHeight: 22,
    textAlign: "center",
    fontWeight: "600",
    marginBottom: 24,
  },
  entryResendButton: {
    minHeight: 28,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  entryResendButtonText: {
    color: "#dd362d",
    fontSize: 16,
    fontWeight: "800",
  },
  entryResendButtonTextDisabled: {
    color: "#d6b2ae",
  },
  entryInlineLoader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  entryInlineLoaderText: {
    color: "#a0a6b3",
    fontSize: 14,
    fontWeight: "700",
  },
  entryErrorText: {
    marginTop: 16,
    color: "#d43d33",
    fontSize: 14,
    lineHeight: 19,
    textAlign: "center",
    fontWeight: "600",
  },
  cityDropdownCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#efeff0",
    marginTop: -6,
    marginBottom: 18,
    overflow: "hidden",
    shadowColor: "#b7bcc9",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  cityDropdownItem: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f2f2",
  },
  cityDropdownItemActive: {
    backgroundColor: "#fff3f2",
  },
  cityDropdownText: {
    color: "#707788",
    fontSize: 16,
    fontWeight: "600",
  },
  cityDropdownTextActive: {
    color: "#db4036",
  },
  phoneGlyph: {
    width: 12,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#a8aebb",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 3,
    paddingBottom: 2,
  },
  phoneGlyphScreen: {
    width: 4,
    height: 1,
    borderRadius: 2,
    backgroundColor: "#a8aebb",
  },
  phoneGlyphDot: {
    width: 3,
    height: 3,
    borderRadius: 999,
    backgroundColor: "#a8aebb",
  },
  searchGlyph: {
    width: 18,
    height: 18,
    position: "relative",
  },
  searchGlyphCircle: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#a8aebb",
    left: 0,
    top: 0,
  },
  searchGlyphHandle: {
    position: "absolute",
    width: 8,
    height: 2,
    borderRadius: 2,
    backgroundColor: "#a8aebb",
    right: 0,
    bottom: 2,
    transform: [{ rotate: "45deg" }],
  },
  chevronGlyph: {
    width: 14,
    height: 14,
    marginLeft: 10,
    position: "relative",
  },
  chevronGlyphOpen: {
    transform: [{ rotate: "180deg" }],
  },
  chevronGlyphLine: {
    position: "absolute",
    width: 8,
    height: 2,
    borderRadius: 2,
    backgroundColor: "#a8aebb",
    top: 6,
  },
  chevronGlyphLineLeft: {
    left: 0,
    transform: [{ rotate: "45deg" }],
  },
  chevronGlyphLineRight: {
    right: 0,
    transform: [{ rotate: "-45deg" }],
  },
  authShell: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 44,
    backgroundColor: palette.bg,
  },
  authHero: {
    borderRadius: 36,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 28,
    overflow: "hidden",
  },
  authHeroOrbLarge: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: "rgba(255,255,255,0.10)",
    top: -90,
    right: -50,
  },
  authHeroOrbSmall: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 150,
    backgroundColor: "rgba(255,255,255,0.08)",
    bottom: -40,
    left: -20,
  },
  authBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  authBrandBadge: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  authBrandBadgeText: {
    color: "#fffaf7",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  authBrandTextWrap: {
    flex: 1,
  },
  authKicker: {
    color: "#fff2ee",
    textTransform: "uppercase",
    letterSpacing: 1.6,
    fontSize: 11,
    marginBottom: 3,
    fontWeight: "700",
  },
  authBrandSubtitle: {
    color: "#ffd7cf",
    fontSize: 13,
    fontWeight: "600",
  },
  authTitle: {
    color: "#fffaf7",
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "800",
    marginBottom: 12,
    maxWidth: 300,
  },
  authSubtitle: {
    color: "#ffd9d1",
    lineHeight: 22,
    fontSize: 15,
    maxWidth: 310,
  },
  authHeroPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 18,
    marginBottom: 18,
  },
  authHeroPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  authHeroPillText: {
    color: "#fff6f2",
    fontSize: 12,
    fontWeight: "700",
  },
  authHeroMetrics: {
    flexDirection: "row",
    gap: 10,
  },
  authHeroMetric: {
    flex: 1,
    borderRadius: 20,
    padding: 14,
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  authHeroMetricValue: {
    color: "#fffaf7",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 4,
  },
  authHeroMetricLabel: {
    color: "#ffd7cf",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  authCardWrap: {
    marginTop: -30,
    paddingHorizontal: 8,
  },
  authCard: {
    backgroundColor: palette.card,
    borderRadius: 30,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: "#3b2017",
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
  },
  authStepRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  authStepPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.panel,
  },
  authStepPillActive: {
    backgroundColor: "#1f2330",
  },
  authStepPillDone: {
    backgroundColor: "#dff2e5",
  },
  authStepPillText: {
    color: palette.subtext,
    fontSize: 12,
    fontWeight: "800",
  },
  authStepPillTextActive: {
    color: "#fffaf7",
  },
  authStepLine: {
    flex: 1,
    height: 1,
    backgroundColor: palette.border,
    marginHorizontal: 10,
  },
  authCardHeader: {
    marginBottom: 8,
  },
  authCardTitle: {
    color: palette.text,
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    marginBottom: 6,
  },
  authCardSubtitle: {
    color: palette.subtext,
    fontSize: 14,
    lineHeight: 20,
  }
};
